language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t binravee/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true binravee/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1c"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-195611311935"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
